url: https://www.mapbox.com
api: https://www.mapbox.com
tileApi: https://api.tiles.mapbox.com
source: docs
permalink: /:categories/:title
baseurl: /mapbox-android-sdk
pygments: true
version: 0.4.0
snapshot: 0.5.0-SNAPSHOT
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
